// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control-error': string;
  'controlError': string;
  'flex-center': string;
  'flex-left': string;
  'flex-right': string;
  'flex-space-between': string;
  'flexCenter': string;
  'flexLeft': string;
  'flexRight': string;
  'flexSpaceBetween': string;
  'form': string;
  'form-cell': string;
  'form-control': string;
  'form-row': string;
  'formCell': string;
  'formControl': string;
  'formRow': string;
}
export const cssExports: CssExports;
export default cssExports;
