// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error-msg': string;
  'errorMsg': string;
  'flex-center': string;
  'flex-left': string;
  'flex-right': string;
  'flex-space-between': string;
  'flexCenter': string;
  'flexLeft': string;
  'flexRight': string;
  'flexSpaceBetween': string;
}
export const cssExports: CssExports;
export default cssExports;
