// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flex-center': string;
  'flex-left': string;
  'flex-right': string;
  'flex-space-between': string;
  'flexCenter': string;
  'flexLeft': string;
  'flexRight': string;
  'flexSpaceBetween': string;
  'popup': string;
  'popup-mask': string;
  'popup-modal': string;
  'popup-modal-wrapper': string;
  'popup-wrapper': string;
  'popupMask': string;
  'popupModal': string;
  'popupModalWrapper': string;
  'popupWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
