// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flex-center': string;
  'flex-left': string;
  'flex-right': string;
  'flex-space-between': string;
  'flexCenter': string;
  'flexLeft': string;
  'flexRight': string;
  'flexSpaceBetween': string;
  'home': string;
  'invite-btn': string;
  'inviteBtn': string;
  'landing': string;
  'slogan': string;
  'sub-slogan': string;
  'subSlogan': string;
}
export const cssExports: CssExports;
export default cssExports;
